apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  labels:
    app: webapp
data:
  NODE_ENV: "production"
  NEXT_PUBLIC_ENV: "production"
  NEXT_PUBLIC_SITE_URL: "https://example.com"
  NEXT_PUBLIC_API_BASE_URL: "https://api.example.com"
  NEXT_PUBLIC_API_TIMEOUT: "120000"
