apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
  labels:
    app: webapp
type: Opaque
data:
  # The values must be base64 encoded.
  # This is a placeholder for your actual API key.
  # To encode your own secret: echo -n 'your-real-api-key' | base64
  NEXT_PUBLIC_API_KEY: eW91ci1zZWNyZXQtYXBpLWtleQ== # base64 encoded "your-secret-api-key"
